modLoader="javafml"
loaderVersion="[${loader_version_min},${loader_version_max})"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker}"
logoFile="icon.png"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL=""
displayURL="${mod_page}"
credits="I'd like to thank all my supporters on Patreon for giving me a reason to continue modding, and you for downloading and playing with this mod"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[50,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version_min},${minecraft_version_max})"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="unionlib"
    mandatory=true
    versionRange="[${unionlib_version_min},${unionlib_version_max})"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="curios"
    mandatory=false
    versionRange="[1.19.2-8.0.0,)"
    ordering="NONE"
    side="BOTH"
